repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        files: ^backend/
        args:
          [
            "-rn",
            "-sn",
            "--rcfile=backend/.pylintrc",
            "--load-plugins=pylint.extensions.docparams",
          ]

  - repo: local
    hooks:
      - id: requirements
        name: requirements
        entry: powershell -Command ".\backend\venv\Scripts\pip.exe freeze > backend/requirements.txt; git add backend/requirements.txt"
        language: system
        pass_filenames: false
        files: ^backend/